name: stocktrade

on:
  push:
    branches: [ main ]

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_KEY  }}
          HOSTNAME : ${{ secrets.HOST_NAME  }}


        run: |
          #Here we will create the private key and we will give the permission to the key
    
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
             sudo systemctl stop stocktrade.service
            fuser -k 8080/tcp
            rm -rf /home/ubuntu/stocktrade
            git clone git@github.com:mojafa/stocktrade.git
            cd /home/ubuntu/stocktrade 
            git checkout main
            git pull origin main 
            mkdir -p /home/ubuntu/logs 
            sudo chmod +x ./deploy.sh
            ./deploy.sh
          '