name: StockTrade Deployment

on:
  push:
    branches: [ "main" ]


jobs:
  #First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_KEY  }}
          HOSTNAME : ${{ secrets.HOST_NAME  }}

        run:
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i StrictHostKeyChecking=no -i private_key ${HOSTNAME}
          cd /home/ubuntu/stocktrade &&
          git checkout main &&
          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main &&
          mvn clean compile package

